In [1]:
import pandas as pd 
import numpy as np

In [6]:
df=pd.read_csv("../data/raw/bank_reviews.csv")
df.tail()

,reviewId,userName,userImage,content,score,thumbsUpCount,reviewCreatedVersion,at,replyContent,repliedAt,appVersion,bank,source
1495,89747566-2b29-492f-9141-0f6ab1695135,Zekariyas Maseresha,https://play-lh.googleusercontent.com/a-/ALV-U...,Its user friendly 🤙🤙 after using this lite app...,5,4,4.0.3,2022-07-18 19:12:44,NaN,NaN,4.0.3,Dashen,Google Play
1496,de9eb417-62b6-46be-9c4c-2d0e839cb4de,TESFAYE ANENE,https://play-lh.googleusercontent.com/a/ACg8oc...,Nice and attractive application developed. Won...,5,5,4.0.3,2022-07-18 16:08:23,NaN,NaN,4.0.3,Dashen,Google Play
1497,ded538c4-7ac6-40e8-9462-7a5c124d9835,Yafet Tadesse,https://play-lh.googleusercontent.com/a-/ALV-U...,Amole lite is very simple for any kind of paym...,5,4,4.0.3,2022-07-18 10:49:53,NaN,NaN,4.0.3,Dashen,Google Play
1498,6dc921a2-231e-4f32-ab9a-bd2bc6ec5a6a,Kaleab Alemu Zeleke,https://play-lh.googleusercontent.com/a-/ALV-U...,በጣም አሪፍ!!! ከቀድሞው የተሻለ ቀለል ያለ app ነው። ተመችቶኛል❤,4,3,4.0.3,2022-07-18 09:38:21,NaN,NaN,4.0.3,Dashen,Google Play
1499,1c01914c-c69b-47d1-8f6b-4ff6984ad5a4,Zerihun Belay,https://play-lh.googleusercontent.com/a-/ALV-U...,I have been waiting for this a long time. Amaz...,5,16,4.0.3,2022-07-16 21:10:12,NaN,NaN,4.0.3,Dashen,Google Play

In [17]:
# Rename and filter columns
df_cleaned = df[['content', 'score', 'at', 'bank', 'source']].copy()
df_cleaned.columns = ['review', 'rating', 'date', 'bank', 'source']

# Format date to YYYY-MM-DD
df_cleaned['date'] = pd.to_datetime(df_cleaned['date']).dt.date

# Drop duplicates and missing review text
df_cleaned = df_cleaned.drop_duplicates(subset=['review', 'bank'])
df_cleaned = df_cleaned.dropna(subset=['review'])

# Save to CSV (Remember to add data/ to .gitignore!)
df_cleaned.to_csv('../data/raw/cleaned_bank_reviews.csv', index=False)
print("Data saved successfully!")

Data saved successfully!

In [18]:
cleaned=pd.read_csv("../data/raw/cleaned_bank_reviews.csv")
cleaned.head()

                          review  rating        date bank       source
0  best app for financial sector       5  2026-05-14  CBE  Google Play
1        it's a good application       5  2026-05-13  CBE  Google Play
2                  thank you cbe       5  2026-05-13  CBE  Google Play
3                        is good       5  2026-05-13  CBE  Google Play
4                            wow       5  2026-05-13  CBE  Google Play